### PR TITLE
removing build folder and updating gitignore file

### PR DESCRIPTION
**Pull request by biharck**
### What
Removing the ‘build’ folder from the actual git repository
### Why
It keeps getting merge conflicts

### CODE REVIEW

**Comment by pieper** [comment]
We should be sure to update the examples - currently dcmjs-org.github.io/examples point to ../../build to get their copy of dcmjs, but that's not going to work.

Probably the best would to move them to a new repository, like dcmjs-examples, that uses the unpkg versions of dcmjs and dicomweb-client (even with specific version tags) so they don't keep breaking.

**Comment by biharck** [comment]
@pieper Good catch. I agree with you. I think the examples should be a new repository and keep the lib self-contained.

**Comment by pieper** [comment]
Thanks - for jumping on this!

**Comment by swederik** [comment]
Closing because I merged this in another PR. Thanks!

**Pull request closed without merging**
