### PR TITLE
Refactor and fragment bug

### PR DESCRIPTION
**Pull request by Ouwen**
Fix for #282.

Also refactors options into dictionary params to maintain public API.
Moved optional parameter tests into separate data-options.test.js
Removed legacy untilTag.test.js

### CODE REVIEW

**Comment by pieper** [comment]
Does this change break the API?

**Comment by Ouwen** [comment]
It shouldn’t break the API (DicomMessage.readFile)

**Comment by Ouwen** [comment]
@pieper the refactor commit will change the function signature of

`DicomMessage.read` and `DicomMessage.readTag`

However, my understanding is that these are largely used internal to the dcmjs package. I've done a sweep to edit any place they are used (tests).

The change puts options like `ignoreErrors`, `untilTag`, and `includeUntilTagValue`, into an `options` param. Future PRs which add options can be made without modifying the function signature.

**Comment by pieper** [comment]
Yes, I agree, they are unlikely to be used outside of the parsing code.  I wonder if the "correct" thing to do would be to change the names of these and similar internal methods to start with an underscore and leave the existing ones as-is but mark them as deprecated.  What do you think?

**Comment by Ouwen** [comment]
I think that makes sense and would be a good notification for anyone still using it that it'll be dropped in the next major version release. I can put up a quick PR for that.

**Comment by Ouwen** [comment]
@pieper let me know if this looks good to you

**Comment by pieper** [comment]
Thanks for this 👍  keeping the API stable makes me more comfortable.

**Pull request merged**
