### PR TITLE
fix(Segmentation): Cascade flag to skipOverlapping for generateToolState to the client

### PR DESCRIPTION
**Pull request by gangaramstyle**
This PR and the recent PR https://github.com/dcmjs-org/dcmjs/pull/183 by @igoroctaviano are the steps I needed to take to get the examples/displaySegmentation/index.html to work locally without errors. The rationale for the changes for this specific PR are explained in https://github.com/dcmjs-org/dcmjs/issues/184.

I'm not sure if lines 64 and 66 in displaySegmentation/index.html are necessary for the hosted netlify examples but I had to do that to test the example locally. I can remove those two lines if it's confirmed that they're unnecessary and would actually break the hosted example.

### CODE REVIEW

**Comment by Punzo** [comment]
LGTM!

**Comment by gangaramstyle** [comment]
can anyone with write permission take a look/merge this change? @swederik @pieper ? More information https://github.com/dcmjs-org/dcmjs/issues/184 and https://github.com/dcmjs-org/dcmjs/issues/183

Also, this is my first PR to an open source project so please forgive me if I'm not following proper protocol in terms of requesting reviews!

**Comment by pieper** [comment]
> Also, this is my first PR to an open source project so please forgive me if I'm not following proper protocol in terms of requesting reviews!

You are doing fine, and thanks for the contributions 👍     Sometimes it takes a while to follow up, and since we are using this code in production we are working to improve our testing so we don't get regressions.  I would need to dig back into the details to do a review but I'm hoping @Punzo and @igoroctaviano are up to speed and make sure we cover all the cases.

**Comment by Punzo** [comment]
@pieper see https://github.com/dcmjs-org/dcmjs/pull/187

**Pull request closed without merging**
