### PR TITLE
fix: several issues with character set handling

### PR DESCRIPTION
**Pull request by richard-viney**
- Fix several character sets not working, e.g. "ISO_IR 13" and "ISO_IR 166"
- Fix warning being shown when the "ISO_IR 6" character set is used
- Add tests for reading encoded string data in several different character sets
- Throw exception on an unsupported character set or multiple character sets rather than logging and continuing on (this can be overridden by setting ignoreErrors)

The new `encodingMapping` was based on code in `pydicom` as well as the DICOM spec.

### CODE REVIEW

**Comment by pieper** [comment]
This is looking good - thanks for the contribution 👍 

Let me know when it's ready to merge.

**Comment by richard-viney** [comment]
The only additional change I think is warranted is to throw an exception on an attempt to use multiple character sets, because this isn't currently supported.

If ignoreErrors is set to true we would allow parsing to proceed and emit a warning similar to the existing one.

Seem reasonable?

**Comment by richard-viney** [comment]
I've added the changes to throw an exception on multiple character sets as well.

Setting `ignoreErrors` to true will allow the code to proceed past any character set issue.

**Comment by richard-viney** [comment]
Good to merge now 👍

**Review by pieper — APPROVED** [review]
Thanks for the contribution 👍

**Pull request merged**
