### PR TITLE
Idc dcmjs 232

### PR DESCRIPTION
**Pull request by Punzo**
This fix https://github.com/dcmjs-org/dcmjs/issues/232  

NOTE1 @fedorov: in the data that you gave me relative to https://github.com/dcmjs-org/dcmjs/issues/232, had segmentation frames with wrong _sopInstanceUid_ in _SourceImageSequence_. So in these cases I added a manual search between the _ImagePositionPatient_ in _PlanePositionSequence_ of the segmentation frame and the _ImagePositionPatient_ for all the source images frames (that have the same _frameOfReferenceUID_). This could still give a wrong results, i.e. two source series, with the same _frameOfReferenceUID_, that have each a frame with the same _ImagePositionPatient_ of _PlanePositionSequence_ of the segmentation frame.

See:
https://github.com/dcmjs-org/dcmjs/compare/master...Punzo:IDC-dcmjs-232?expand=1#diff-077798721d0df020ee8184a2f54d4459dba916e19c86ac0f0aecc4e6ea80bf2fR624-R661

I am not sure is ideal to have this "manual" search. What do you think about it?

NOTE2 @pieper  : I also fixed a regression from https://github.com/dcmjs-org/dcmjs/commit/70b24332783d63c9db2ed21d512d9f7b526c5222 ( see https://github.com/dcmjs-org/dcmjs/compare/master...Punzo:IDC-dcmjs-232?expand=1#diff-077798721d0df020ee8184a2f54d4459dba916e19c86ac0f0aecc4e6ea80bf2fR1258-R1273)

### CODE REVIEW

**Comment by Punzo** [comment]
NOTE 2 in https://github.com/dcmjs-org/dcmjs/pull/234#issue-1101774569 has been addressed in https://github.com/dcmjs-org/dcmjs/pull/236

**Comment by Punzo** [comment]
> @Punzo LGTM but one thing I'm not sure, why the package-lock has changed?

fixed

**Comment by Punzo** [comment]
@pieper may you review/merge, please?

**Review by pieper — APPROVED** [review]
LGTM 👍

**Pull request merged**
