### PR TITLE
Fix rotation issues for different segs.

### PR DESCRIPTION
**Pull request by JamesAPetts**
RE: https://github.com/OHIF/Viewers/issues/2003

Fixes SEG mapping issues for the cornerstone segmentation adapter, when the data is rotated relative to the source data.

### CODE REVIEW

**Comment by fedorov** [comment]
@pieper let's not rush this into the IDC MVP fork this week (if it gets merged) - we don't have any data included in MVP that would benefit from this fix, and we need to test it first.

**Comment by pieper** [comment]
@fedorov I'd rather integrate this so that we can test it and fix it in OHIF if needed.  Otherwise we'd need to start cherry-picking commits and would have a complex divergence in our fork.

**Comment by fedorov** [comment]
Ok, now that it's merged - let's start testing it. Can you let me know when the sandbox is updated?

**Comment by JamesAPetts** [comment]
> Ok, now that it's merged - let's start testing it.

This is just the dcmjs implementation. I need to merge this to OHIF, and then update the IDC fork. I'll ping you two when its done 👍 .

**Pull request merged**
