### PR TITLE
Expose the anonymizer module which contains `cleanTags`, closes #172

### LINKED ISSUE #172: Expose the `cleanTags` function from anonymizer
Hi,

Thank you very much for a wonderful library. We would like to use the anonymization feature of `dcmjs` and would like the `cleanTags` function exposed.

I'll submit a PR for this - hopefully it gets approved :)

### PR DESCRIPTION
**Pull request by wheresvic**

### CODE REVIEW

**Comment by pieper** [comment]
LGTM 👍 

@swederik do you have any thoughts on this?

**Comment by swederik** [comment]
Only that I have a newer version of this for another project which I need to push back. I am definitely in favour of exposing it.

**Comment by wheresvic** [comment]
That's cool! So we would appreciate if it could be merged in so that I can start using the feature and then @swederik you could swap the implementation later and benefit from the unit test that this PR comes with :)

What do you think?

**Comment by pieper** [comment]
It makes sense to expose all the options, since in many deid use cases you may need to add custom logic if you wish to preserve some of the semantics of the metadata.

**Comment by pieper** [comment]
Shoot, I forgot to check the commit message.  If it had started with `feat` it would have triggered the automatic feature release.  This will get rolled up into the next release, or if you want it released sooner just push a dummy PR with a commit that follows [the semantic versioning pattern.](https://github.com/dcmjs-org/dcmjs#for-maintainers)

**Comment by wheresvic** [comment]
> Shoot, I forgot to check the commit message. If it had started with `feat` it would have triggered the automatic feature release. This will get rolled up into the next release, or if you want it released sooner just push a dummy PR with a commit that follows [the semantic versioning pattern.](https://github.com/dcmjs-org/dcmjs#for-maintainers)

Ah sorry! Will do :)

**Pull request merged**
