### PR TITLE
IDC2345: add tollerance parameter to generateToolState

### PR DESCRIPTION
**Pull request by Punzo**
Fix https://github.com/OHIF/Viewers/issues/2345#issuecomment-821910646 , @pieper @igoroctaviano could you please review and merge, please? thanks!

### CODE REVIEW

**Comment by pieper** [comment]
Hi @Punzo - this looks good but I wonder if it's time to add some extra robustness on the error checking to better support animal scans or microscopy.  There are a lot of of web pages on this but this one seemed like a nice summary: https://floating-point-gui.de/errors/comparison/

Do you think it's worth the extra effort?

**Comment by Punzo** [comment]
> Hi @Punzo - this looks good but I wonder if it's time to add some extra robustness on the error checking to better support animal scans or microscopy. There are a lot of of web pages on this but this one seemed like a nice summary: https://floating-point-gui.de/errors/comparison/
> 
> Do you think it's worth the extra effort?

yes tomorrow I will implement it.

**Comment by Punzo** [comment]
@pieper  done in https://github.com/dcmjs-org/dcmjs/pull/200/commits/19042958b59a1968892d18b238215f5d01b49712

**Comment by Punzo** [comment]
> Yes, looks good. It could make sense for this to be in a more generally accessible location since the same function could be used for things like slice sorting or other validation.

ok I will move to https://github.com/dcmjs-org/dcmjs/tree/master/src/utilities/orientation

> I think it would be good to reference that article that @pieper mentioned as the inspiration for this.

I already put the link in the description https://github.com/dcmjs-org/dcmjs/pull/200/files#diff-077798721d0df020ee8184a2f54d4459dba916e19c86ac0f0aecc4e6ea80bf2fR1442 . But if you didn't noticed it, I did not highlithed it enough. I add some description.

> Should this be "tolerance" with single "l"?

Definitely, thanks for catching the typo.

**Comment by Punzo** [comment]
@pieper @fedorov done in https://github.com/dcmjs-org/dcmjs/pull/200/commits/0f1680eacb05618bd53394ec8c4090b2f85e1eca

**Review by pieper — APPROVED** [review]

**Comment by pieper** [comment]
👍

**Pull request merged**
