### PR TITLE
#194 encapsulation is applied for only PixelData

### PR DESCRIPTION
**Pull request by codepage949**
after this fix, overlay is visible on compressed image transfer syntax.

it seems enough that encapsulation is applied for only PixelData.

is there another case to apply encapsulation?

### CODE REVIEW

**Comment by codepage949** [comment]
from #194

**Comment by pieper** [comment]
Hi - thanks for digging into this and that solution looks simple.  But I haven't got a clear idea whether it would have side effects on other studies.

Can you write a test following the format of the other tests in dcmjs?  Were you able to run the existing test suite with your change?

**Comment by codepage949** [comment]
@pieper added test and passed with other tests, please review.

**Comment by pieper** [comment]
Thanks for adding the test 👍 

Since this is in a deep part of the code that I know people are using in production I'm trying to be extra thoughtful about merges.  @Punzo and @igoroctaviano could you have a quick look to see if you think this is okay to merge?

**Comment by pieper** [comment]
@codepage949 could you provide some extra context for this?

* what is the target use case?
* where do these overlays come from? 
* what system is expected to read them?
* how do other toolkits handle this data?  Have you tried pydicom, dcmtk, gdcm, others?

Thanks in advance

**Comment by codepage949** [comment]
* what is the target use case?

    * denoting areas over image

* where do these overlays come from?

    * in my case, made it by myself. please refer to [#194](https://github.com/dcmjs-org/dcmjs/issues/194)

* what system is expected to read them?

    * ideally, any dicom viewer that complies with standards

* how do other toolkits handle this data? Have you tried pydicom, dcmtk, gdcm, others?

    * in pydicom, overlay data is inserted without any transformation even when transfer syntax is what needs encapsulation.

[side note]

i opened a dicom file which has private tag of UN vr with dcmjs and saved without any changes.

and then, opened dicom file saved by dcmjs on weasis, aliza viewer, it failed to open.

i guess it is because dcmjs apply encapsulation on private tag of UN vr too. [tag.js#L111](https://github.com/dcmjs-org/dcmjs/blob/91c70dd12e3c42f7fc542a195ab759ad763196b5/src/Tag.js#L111)

**Comment by codepage949** [comment]
according to [this](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_A.4.html), i interpreted that pixel data is the only one that can be encapsulated.

**Comment by pieper** [comment]
> according to [this](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_A.4.html), i interpreted that pixel data is the only one that can be encapsulated.
> 
> > Pixel Data (7FE0,0010) may be encapsulated or native.
> 
> > Overlay Data (60xx,3000) and other tags mentioned in the document.
> > ... shall be encoded in Little Endian.

Yes, I see your logic now @codepage949.

@jmhmd I think this is also related to some code you added.  Can you review and comment?

**Pull request merged**
