### PR TITLE
fix(generate-dictionary): update generate script to use https and regenerate source dictionary

### PR DESCRIPTION
**Pull request by craigberry1**
- Fixes issue running generate-dictionary script
- Update source dictionary to latest version of the DICOM spec

### CODE REVIEW

**Comment by craigberry1** [comment]
Hey @pieper are you able to take a look at this?

**Comment by craigberry1** [comment]
Bump @pieper

**Review by pieper — APPROVED** [review]
Thanks for doing this 👍 

Sorry for the slow response - I was away and didn't have access to github for a while.

**Comment by craigberry1** [comment]
> Thanks for doing this 👍
> 
> Sorry for the slow response - I was away and didn't have access to github for a while.

No problem! Thanks for getting it merged.

**Pull request merged**
